### ISSUE TITLE
Authentication error is not very clear

### ISSUE THREAD

**Issue by aabedraba** [speakeasy-api/speakeasy-typescript-sdk#7]
Hi team,
thanks for the great stuff! 

When I tried the typescript library and configured the APIKey, I made a mistake with the key and the resulting error wasn't very helpful and didn't allow me to understand what the error was about. 

This is the resulting error: 
```sh
Error: 2 UNKNOWN: err_unauthorized: unauthorized -- err_not_found: not found -- sql: no rows in result set
    at Object.callErrorFromStatus (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@grpc/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@grpc/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.ingest (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at GRPCClient.send (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@speakeasy-api/speakeasy-typescript-sdk/dist/transport.js:50:21)
    at SpeakeasySDK.send (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@speakeasy-api/speakeasy-typescript-sdk/dist/speakeasy.js:34:25)
    at /Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@speakeasy-api/speakeasy-typescript-sdk/dist/middleware/common/middleware.js:55:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/aabedraba/github/aabedraba/speakeasy-demo/node_modules/@speakeasy-api/speakeasy-typescript-sdk/dist/middleware/common/middleware.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'err_unauthorized: unauthorized -- err_not_found: not found -- sql: no rows in result set',
  metadata: Metadata {
    internalRepr: Map(4) {
      'date' => [Array],
      'content-type' => [Array],
      'content-length' => [Array],
      'strict-transport-security' => [Array]
    },
    options: {}
  }
}
```

Once I fixed my APIKey (which was wrapped with extra quotes) the error disappeared. 

Suggestion to simplify this in a way that nudges developers to look into the configured APIKey?

**Comment by alexadrake** [comment]
Yeah, I see that's not a terribly clear error message; definitely something we can prioritize. 

Also want to point you toward our [public slack](https://join.slack.com/t/speakeasy-dev/shared_invite/zt-1fdrk1dly-dzChN4ok~lSObocU6w4Usg) where we provide support and make announcements and such.

**Comment by aabedraba** [comment]
@alexadrake glad to know!! Amazing pace :)
